/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TestRouteImport } from './routes/test'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReviseRouteImport } from './routes/revise'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FormulasRouteImport } from './routes/formulas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectSubjectIdRouteImport } from './routes/subject.$subjectId'
import { Route as SubjectSubjectIdChapterSlugRouteImport } from './routes/subject.$subjectId.$chapterSlug'
import { Route as FormulasSubjectIdChapterSlugRouteImport } from './routes/formulas.$subjectId.$chapterSlug'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviseRoute = ReviseRouteImport.update({
  id: '/revise',
  path: '/revise',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulasRoute = FormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdRoute = SubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdChapterSlugRoute =
  SubjectSubjectIdChapterSlugRouteImport.update({
    id: '/$chapterSlug',
    path: '/$chapterSlug',
    getParentRoute: () => SubjectSubjectIdRoute,
  } as any)
const FormulasSubjectIdChapterSlugRoute =
  FormulasSubjectIdChapterSlugRouteImport.update({
    id: '/$subjectId/$chapterSlug',
    path: '/$subjectId/$chapterSlug',
    getParentRoute: () => FormulasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formulas': typeof FormulasRouteWithChildren
  '/profile': typeof ProfileRoute
  '/revise': typeof ReviseRoute
  '/search': typeof SearchRoute
  '/test': typeof TestRoute
  '/vault': typeof VaultRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRouteWithChildren
  '/formulas/$subjectId/$chapterSlug': typeof FormulasSubjectIdChapterSlugRoute
  '/subject/$subjectId/$chapterSlug': typeof SubjectSubjectIdChapterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formulas': typeof FormulasRouteWithChildren
  '/profile': typeof ProfileRoute
  '/revise': typeof ReviseRoute
  '/search': typeof SearchRoute
  '/test': typeof TestRoute
  '/vault': typeof VaultRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRouteWithChildren
  '/formulas/$subjectId/$chapterSlug': typeof FormulasSubjectIdChapterSlugRoute
  '/subject/$subjectId/$chapterSlug': typeof SubjectSubjectIdChapterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formulas': typeof FormulasRouteWithChildren
  '/profile': typeof ProfileRoute
  '/revise': typeof ReviseRoute
  '/search': typeof SearchRoute
  '/test': typeof TestRoute
  '/vault': typeof VaultRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRouteWithChildren
  '/formulas/$subjectId/$chapterSlug': typeof FormulasSubjectIdChapterSlugRoute
  '/subject/$subjectId/$chapterSlug': typeof SubjectSubjectIdChapterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/formulas'
    | '/profile'
    | '/revise'
    | '/search'
    | '/test'
    | '/vault'
    | '/subject/$subjectId'
    | '/formulas/$subjectId/$chapterSlug'
    | '/subject/$subjectId/$chapterSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/formulas'
    | '/profile'
    | '/revise'
    | '/search'
    | '/test'
    | '/vault'
    | '/subject/$subjectId'
    | '/formulas/$subjectId/$chapterSlug'
    | '/subject/$subjectId/$chapterSlug'
  id:
    | '__root__'
    | '/'
    | '/formulas'
    | '/profile'
    | '/revise'
    | '/search'
    | '/test'
    | '/vault'
    | '/subject/$subjectId'
    | '/formulas/$subjectId/$chapterSlug'
    | '/subject/$subjectId/$chapterSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormulasRoute: typeof FormulasRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReviseRoute: typeof ReviseRoute
  SearchRoute: typeof SearchRoute
  TestRoute: typeof TestRoute
  VaultRoute: typeof VaultRoute
  SubjectSubjectIdRoute: typeof SubjectSubjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revise': {
      id: '/revise'
      path: '/revise'
      fullPath: '/revise'
      preLoaderRoute: typeof ReviseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulas': {
      id: '/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId': {
      id: '/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof SubjectSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId/$chapterSlug': {
      id: '/subject/$subjectId/$chapterSlug'
      path: '/$chapterSlug'
      fullPath: '/subject/$subjectId/$chapterSlug'
      preLoaderRoute: typeof SubjectSubjectIdChapterSlugRouteImport
      parentRoute: typeof SubjectSubjectIdRoute
    }
    '/formulas/$subjectId/$chapterSlug': {
      id: '/formulas/$subjectId/$chapterSlug'
      path: '/$subjectId/$chapterSlug'
      fullPath: '/formulas/$subjectId/$chapterSlug'
      preLoaderRoute: typeof FormulasSubjectIdChapterSlugRouteImport
      parentRoute: typeof FormulasRoute
    }
  }
}

interface FormulasRouteChildren {
  FormulasSubjectIdChapterSlugRoute: typeof FormulasSubjectIdChapterSlugRoute
}

const FormulasRouteChildren: FormulasRouteChildren = {
  FormulasSubjectIdChapterSlugRoute: FormulasSubjectIdChapterSlugRoute,
}

const FormulasRouteWithChildren = FormulasRoute._addFileChildren(
  FormulasRouteChildren,
)

interface SubjectSubjectIdRouteChildren {
  SubjectSubjectIdChapterSlugRoute: typeof SubjectSubjectIdChapterSlugRoute
}

const SubjectSubjectIdRouteChildren: SubjectSubjectIdRouteChildren = {
  SubjectSubjectIdChapterSlugRoute: SubjectSubjectIdChapterSlugRoute,
}

const SubjectSubjectIdRouteWithChildren =
  SubjectSubjectIdRoute._addFileChildren(SubjectSubjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormulasRoute: FormulasRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReviseRoute: ReviseRoute,
  SearchRoute: SearchRoute,
  TestRoute: TestRoute,
  VaultRoute: VaultRoute,
  SubjectSubjectIdRoute: SubjectSubjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
